### PR TITLE
Adds explicit runtime fsync option for MPIIO, HDF5 and serial IO

### LINKED ISSUE #31: Add runtime option on Lustre caching to benchio tests
At the moment it is up to the system if Lustre client caching is used or not which can lead to inconsistencies with test performance. We should update the benchio source code to allow the test to switch caching off at runtime for all the different tests.

For MPIIO: 

```
  call MPI_File_sync(fh,ierr)
  call MPI_File_close(fh, ierr)
```

For HDF5:

```
  ! Close the file.
  CALL h5fflush_f( file_id , H5F_SCOPE_GLOBAL_F,ierr )
  CALL h5fclose_f(file_id, ierr)
```

For file-per-process:

```
! Declare the interface for POSIX fsync function
  interface
    function fsync (fd) bind(c,name="fsync")
    use iso_c_binding, only: c_int
      integer(c_int), value :: fd
      integer(c_int) :: fsync
    end function fsync
  end interface

...file writing...

  ! Flush and sync
  flush(10)
  ret = fsync(fnum(10))

  ! Handle possible error
  if (ret /= 0) stop "Error calling FSYNC"
```

### PR DESCRIPTION
**Pull request by aturner-epcc**
Enables test to specify, at runtime, that files should be explicitly synced to eliminate effects from client-side cache. Final option keyword to enable this is `fsync`. fsync is disabled by default.

Closes #31

### CODE REVIEW

**Comment by aturner-epcc** [comment]
Also, enables fsync for most benchio tests

**Comment by lucaparisi91** [comment]
I have been able to run the reframe tests and they sync call seems to take effect ( checked output of BenchioFPP32Nodes , BenchioMPIIOUCX32OptNodes). Tests starting in lower case benchio seem to be broken. I also get a bunch of warnings 

```bash
WARNING: skipping evaluation of performance variable 'fullstriped_mpiio_bw': not enough matches of pattern 'Writing to fullstriped/mpiio\\.dat\\W*\\n\\W*time\\W*=\\W*\\d+.\\d*\\W*,\\W*rate\\W*=\\W*(\\d+.\\d*)' in file 'rfm_job.out' so as to extract item 0
WARNING: skipping evaluation of performance variable 'fullstriped_mpiio_time': not enough matches of pattern 'Writing to fullstriped/mpiio\\.dat\\W*\\n\\W*time\\W*=\\W*(\\d+.\\d*)\\W*,\\W*rate\\W*=\\W*\\d+.\\d*' in file 'rfm_job.out' so as to extract item 0
```
The hdf5 performance result seem to be OK though.

**Comment by aturner-epcc** [comment]
Those error messages typically indicate that the test job was killed at walltime so the benchmark never completed.

**Comment by aturner-epcc** [comment]
The sync option means that some jobs may take longer to complete than with caching so I will increase the maximum walltime in tests just in case.

**Pull request merged**
